# ./backend/Dockerfile.dev
FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y gcc libpq-dev postgresql-client && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Files will be bind-mounted, but we copy them just in case
COPY . .
EXPOSE 8000

# Start with hot-reload enabled
# Run migrations automatically before starting the dev server
CMD ["sh", "-c", "sleep 3 && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000", "--reload"]