"""Initial master schema

Revision ID: 94fd17150503
Revises: 
Create Date: 2026-03-16 09:49:34.570345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fd17150503'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('currency_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('symbol', sa.String(length=5), nullable=True),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_currency_options_id'), 'currency_options', ['id'], unique=False)
    op.create_table('unit_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=10), nullable=True),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_unit_options_id'), 'unit_options', ['id'], unique=False)
    op.create_table('yards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yards_id'), 'yards', ['id'], unique=False)
    op.create_index(op.f('ix_yards_name'), 'yards', ['name'], unique=True)
    op.create_table('deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deductions_date'), 'deductions', ['date'], unique=False)
    op.create_index(op.f('ix_deductions_id'), 'deductions', ['id'], unique=False)
    op.create_table('pickups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('yard', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deduction', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickups_date'), 'pickups', ['date'], unique=False)
    op.create_index(op.f('ix_pickups_id'), 'pickups', ['id'], unique=False)
    op.create_table('metal_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=True),
    sa.Column('metal_name', sa.String(), nullable=True),
    sa.Column('net_weight', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(length=10), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metal_items_id'), 'metal_items', ['id'], unique=False)
    op.create_index(op.f('ix_metal_items_metal_name'), 'metal_items', ['metal_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metal_items_metal_name'), table_name='metal_items')
    op.drop_index(op.f('ix_metal_items_id'), table_name='metal_items')
    op.drop_table('metal_items')
    op.drop_index(op.f('ix_pickups_id'), table_name='pickups')
    op.drop_index(op.f('ix_pickups_date'), table_name='pickups')
    op.drop_table('pickups')
    op.drop_index(op.f('ix_deductions_id'), table_name='deductions')
    op.drop_index(op.f('ix_deductions_date'), table_name='deductions')
    op.drop_table('deductions')
    op.drop_index(op.f('ix_yards_name'), table_name='yards')
    op.drop_index(op.f('ix_yards_id'), table_name='yards')
    op.drop_table('yards')
    op.drop_index(op.f('ix_unit_options_id'), table_name='unit_options')
    op.drop_table('unit_options')
    op.drop_index(op.f('ix_currency_options_id'), table_name='currency_options')
    op.drop_table('currency_options')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
